### ISSUE TITLE
My approach to the Linode API

### ISSUE THREAD

**Issue by RoccoHoward** [illblew/php-linode-unofficial#7]
Hello!

Just wanted to drop a message and connect you with my attempt. I've had to take time off this project, so hasn't been finished, but it's a good start. (I was manually converting the api into spec docs, but plan on automatically parsing the existing api spec and then generating it from that).

https://github.com/hnhdigital-os/php-linode-api

**Comment by illblew** [comment]
Thanks for the heads-up, looks like a neat approach! I actually looked at your repo previously and have it on my master list of tools supporting the new Linode API. I'll be sure to try it out in the near future and if we end up with some type of public list I'll be sure to give it a mention.

**Comment by RoccoHoward** [comment]
Great, thanks! Appreciate it.
